### ISSUE TITLE
KS (ks_arch_x86, ks_mode_64

### ISSUE THREAD

**Issue by NyshMy** [samsonpianofingers/BadTooth#2]
How to convert the assembly code of 64 bit program into byte set? I tested KS (ks_arch_x86, ks_mode_64). Many sink codes return none

**Comment by GrandpaGameHacker** [comment]
if you're attached to a 64bit process, BadTooth should already select the appropriate disassembler/assembler types
![image](https://user-images.githubusercontent.com/23288711/172054905-2ef770c2-a97a-4bf7-8dab-12a8f8ad1561.png)
